import { createFileRoute } from "@tanstack/react-router";
import { Card, CardTitle, Chip, PopButton, SectionNote, Stat } from "@/components/sim/ui";
import { createBatch, runSorting, simulateSorting } from "@/lib/simulation/engine";
import { useSim } from "@/lib/simulation/react";
import { kg } from "@/lib/simulation/format";
import { CATEGORY_MAP } from "@/lib/simulation/config";

export const Route = createFileRoute("/centers")({
  head: () => ({
    meta: [
      { title: "Simulated Collection Centers — EcoCycle" },
      {
        name: "description",
        content:
          "Fictional EcoCycle collection centers with simulated capacity, demo inventory records and a sorting simulation.",
      },
      { property: "og:title", content: "Simulated Collection Centers — EcoCycle" },
      {
        property: "og:description",
        content: "Demo centers, simulated storage capacity and simulated sorting results.",
      },
    ],
  }),
  component: CentersPage,
});

function CentersPage() {
  const s = useSim();
  const stored = s.inventory.filter((i) => i.status === "STORED");
  const sortingPreview = simulateSorting(stored, s.settings.factors);
  const inputTotal = stored.reduce((t, i) => t + i.weightKg, 0);

  return (
    <div className="space-y-6">
      <header>
        <h1 className="font-display text-4xl font-bold">Simulated Collection Centers</h1>
        <SectionNote>
          Capacity, inventory and sorting outputs below are simulated values generated by the demo engine.
        </SectionNote>
      </header>

      <section className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <Stat label="Demo Centers" value={s.centers.length} />
        <Stat label="Simulated Stored Weight" value={kg(s.centers.reduce((t, c) => t + c.inventoryKg, 0))} />
        <Stat label="Demo Inventory Records" value={s.inventory.length} />
        <Stat label="Awaiting Simulated Sorting" value={stored.length} tone="text-coral" />
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        {s.centers.map((c) => {
          const available = Math.max(0, c.capacityKg - c.inventoryKg);
          const pct = Math.min(100, Math.round((c.inventoryKg / c.capacityKg) * 100));
          const queue = s.inventory.filter((i) => i.centerId === c.id && i.status !== "PROCESSED").length;
          return (
            <Card key={c.id}>
              <CardTitle title={c.name} badge={<Chip tone={pct > 90 ? "coral" : "lime"}>{pct}% full</Chip>} />
              <div className="h-3 w-full overflow-hidden rounded-full bg-cream">
                <div
                  className="h-full rounded-full bg-leaf transition-all"
                  style={{ width: `${pct}%` }}
                />
              </div>
              <dl className="mt-4 space-y-1.5 text-sm">
                <Row label="Simulated capacity" value={kg(c.capacityKg)} />
                <Row label="Simulated current" value={kg(c.inventoryKg)} />
                <Row label="Simulated available" value={kg(available)} />
                <Row label="Processing queue" value={`${queue} demo items`} />
              </dl>
              <div className="mt-4 flex flex-wrap gap-2">
                <PopButton tone="outline" onClick={() => runSorting(c.id)}>
                  Run Sorting Simulation
                </PopButton>
                <PopButton tone="ink" onClick={() => createBatch(c.id)}>
                  Create Batch
                </PopButton>
              </div>
            </Card>
          );
        })}
      </section>

      <section className="grid gap-6 lg:grid-cols-12">
        <Card className="lg:col-span-5">
          <CardTitle title="Sorting Simulation Preview" badge={<Chip tone="sun">Simulated Sorting Result</Chip>} />
          <SectionNote>
            Input total always equals output total. Input {kg(inputTotal)} across {stored.length} stored demo items.
          </SectionNote>
          <div className="mt-4 space-y-2">
            <Bar label="Reusable" value={sortingPreview.reusable} total={inputTotal} tone="bg-leaf" />
            <Bar label="Recyclable" value={sortingPreview.recyclable} total={inputTotal} tone="bg-sky" />
            <Bar label="Hazardous" value={sortingPreview.hazardous} total={inputTotal} tone="bg-coral" />
            <Bar label="Non-Recyclable / Residual" value={sortingPreview.residual} total={inputTotal} tone="bg-ink" />
          </div>
        </Card>

        <Card className="lg:col-span-7">
          <CardTitle title="Simulated Inventory" badge={<Chip tone="cream">Demo Data</Chip>} />
          <div className="max-h-[420px] overflow-auto">
            <table className="w-full text-left text-sm">
              <thead className="text-[11px] tracking-wide text-muted-foreground uppercase">
                <tr>
                  <th className="py-2">Record</th>
                  <th>Item</th>
                  <th>Weight</th>
                  <th>Condition</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {s.inventory.slice(0, 60).map((i) => (
                  <tr key={i.id} className="border-t border-border/60">
                    <td className="py-2 font-mono text-[11px]">{i.id}</td>
                    <td>{CATEGORY_MAP[i.category].label}</td>
                    <td className="font-mono text-xs">{kg(i.weightKg)}</td>
                    <td className="text-xs">{i.condition}</td>
                    <td>
                      <Chip tone={i.status === "PROCESSED" ? "lime" : "cream"}>{i.status}</Chip>
                    </td>
                  </tr>
                ))}
                {s.inventory.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="py-6 text-center text-sm text-muted-foreground">
                      No simulated inventory yet — launch the demo to generate records.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </Card>
      </section>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-3">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="font-mono text-xs font-semibold">{value}</dd>
    </div>
  );
}

function Bar({ label, value, total, tone }: { label: string; value: number; total: number; tone: string }) {
  const pct = total > 0 ? Math.round((value / total) * 100) : 0;
  return (
    <div>
      <div className="flex justify-between text-xs font-semibold">
        <span>{label}</span>
        <span className="font-mono">{kg(value)}</span>
      </div>
      <div className="mt-1 h-2.5 w-full overflow-hidden rounded-full bg-cream">
        <div className={`h-full rounded-full ${tone}`} style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}
