/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as ControlRouteImport } from './routes/control'
import { Route as PickupsRouteImport } from './routes/pickups'
import { Route as RecyclingRouteImport } from './routes/recycling'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as VerifySimulationCertificateIdRouteImport } from './routes/verify.simulation.$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsRoute = PickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclingRoute = RecyclingRouteImport.update({
  id: '/recycling',
  path: '/recycling',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySimulationCertificateIdRoute =
  VerifySimulationCertificateIdRouteImport.update({
    id: '/verify/simulation/$certificateId',
    path: '/verify/simulation/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/centers': typeof CentersRoute
  '/control': typeof ControlRoute
  '/pickups': typeof PickupsRoute
  '/recycling': typeof RecyclingRoute
  '/rewards': typeof RewardsRoute
  '/verify/simulation/$certificateId': typeof VerifySimulationCertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/centers': typeof CentersRoute
  '/control': typeof ControlRoute
  '/pickups': typeof PickupsRoute
  '/recycling': typeof RecyclingRoute
  '/rewards': typeof RewardsRoute
  '/verify/simulation/$certificateId': typeof VerifySimulationCertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/centers': typeof CentersRoute
  '/control': typeof ControlRoute
  '/pickups': typeof PickupsRoute
  '/recycling': typeof RecyclingRoute
  '/rewards': typeof RewardsRoute
  '/verify/simulation/$certificateId': typeof VerifySimulationCertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/centers'
    | '/control'
    | '/pickups'
    | '/recycling'
    | '/rewards'
    | '/verify/simulation/$certificateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/centers'
    | '/control'
    | '/pickups'
    | '/recycling'
    | '/rewards'
    | '/verify/simulation/$certificateId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/centers'
    | '/control'
    | '/pickups'
    | '/recycling'
    | '/rewards'
    | '/verify/simulation/$certificateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CentersRoute: typeof CentersRoute
  ControlRoute: typeof ControlRoute
  PickupsRoute: typeof PickupsRoute
  RecyclingRoute: typeof RecyclingRoute
  RewardsRoute: typeof RewardsRoute
  VerifySimulationCertificateIdRoute: typeof VerifySimulationCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups': {
      id: '/pickups'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof PickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycling': {
      id: '/recycling'
      path: '/recycling'
      fullPath: '/recycling'
      preLoaderRoute: typeof RecyclingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/simulation/$certificateId': {
      id: '/verify/simulation/$certificateId'
      path: '/verify/simulation/$certificateId'
      fullPath: '/verify/simulation/$certificateId'
      preLoaderRoute: typeof VerifySimulationCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CentersRoute: CentersRoute,
  ControlRoute: ControlRoute,
  PickupsRoute: PickupsRoute,
  RecyclingRoute: RecyclingRoute,
  RewardsRoute: RewardsRoute,
  VerifySimulationCertificateIdRoute: VerifySimulationCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
